//充值明细相关的action type
export const ADD_RECORD_TO_RECHARGE_RECORD = 'ADD_RECORD_TO_RECHARGE_RECORD';
export type ADD_RECORD_TO_RECHARGE_RECORD = typeof ADD_RECORD_TO_RECHARGE_RECORD;

//account相关的action type
export const BUY_LESSON = 'BUY_LESSON';
export type BUY_LESSON = typeof BUY_LESSON;
export const RECHARGE = 'RECHARGE';
export type RECHARGE = typeof RECHARGE;

//mineItemDateSource相关的action type
export const ADD_DATA_TO_MINE_PAGE = 'ADD_DATA_TO_MINE_PAGE';
export type ADD_DATA_TO_MINE_PAGE = typeof ADD_DATA_TO_MINE_PAGE;
export const SET_IS_DOTED_TO_TRUE = 'SET_IS_DOTED_TO_TRUE';
export type SET_IS_DOTED_TO_TRUE = typeof SET_IS_DOTED_TO_TRUE;
export const SET_IS_DOTED_TO_FALSE = 'SET_IS_DOTED_TO_FALSE';
export type SET_IS_DOTED_TO_FALSE = typeof SET_IS_DOTED_TO_FALSE;

//studyItem相关的action type
export const ADD_PURCHASED_LESSONS_TO_STUDY_PAGE = 'ADD_PURCHASED_LESSONS_TO_STUDY_PAGE';
export type ADD_PURCHASED_LESSONS_TO_STUDY_PAGE = typeof ADD_PURCHASED_LESSONS_TO_STUDY_PAGE;

//讲堂 -》 训练营相关的action type
export const ADD_DATA_TO_PRACTICE_CAMP = 'ADD_DATA_TO_PRACTICE_CAMP';
export type ADD_DATA_TO_PRACTICE_CAMP = typeof ADD_DATA_TO_PRACTICE_CAMP;
export const SET_PRACTICE_CAMP_TO_BE_PURCHASED = 'SET_PRACTICE_CAMP_TO_BE_PURCHASED';
export type SET_PRACTICE_CAMP_TO_BE_PURCHASED = typeof SET_PRACTICE_CAMP_TO_BE_PURCHASED;

//courseLessonItem相关的action type
export const ADD_DATA_TO_COURSE_LESSON = 'ADD_DATA_TO_COURSE_LESSON';
export type ADD_DATA_TO_COURSE_LESSON = typeof ADD_DATA_TO_COURSE_LESSON;
export const SET_LESSON_TO_BE_PURCHASED = 'SET_LESSON_TO_BE_PURCHASED';
export type SET_LESSON_TO_BE_PURCHASED = typeof SET_LESSON_TO_BE_PURCHASED;
export const REFRESH_COURSE_LESSON = 'REFRESH_COURSE_LESSON';
export type REFRESH_COURSE_LESSON = typeof REFRESH_COURSE_LESSON;